# Generated by Django 5.2.1 on 2025-05-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolioapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=0.0008888888888888889, upload_to='img'),
            preserve_default=False,
        ),
    ]
